### ISSUE TITLE
Error in the renderSymbol function

### ISSUE THREAD

**Issue by arturhenryy** [intercom/contentful-typescript-codegen#12]
Hello I get the following error when letting your script run.

```
TypeError: Cannot read property 'find' of undefined
    at Object.renderSymbol (/Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:124:42)
    at /Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:218:58
    at Array.map (<anonymous>)
    at renderContentTypeFields (/Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:204:10)
    at renderContentType (/Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:191:18)
    at /Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:262:61
    at Array.map (<anonymous>)
    at renderAllContentTypes (/Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:262:25)
    at /Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:248:25
    at step (/Users/anagenrauft/dev/carfax-web/carfax-web-frontend-website-nextjs/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:68:23)
error Command failed with exit code 1.
```

**Comment by arturhenryy** [comment]
so the error comes from here
```
function renderSymbol(field) {
    console.log(field);
    var inValidation = field.**validations.find**(function (validation) { return !!validation.in; });
    if (inValidation) {
        return renderUnionValues(inValidation.in.map(function (value) { return "'" + value + "'"; }));
    }
    else {
        return "string";
    }
}
```
because field.validations is not defined

this is my console output of **field** before it break

```
{
  id: 'text',
  name: 'Text',
  type: 'Text',
  localized: false,
  required: true,
  disabled: false,
  omitted: false
}
```

**Comment by stevenpetryk** [comment]
Hey there, thanks for submitting this! 

What does your `getContentEnvironment.js` file look like? I think your issue might be that you are exporting a Content Delivery API client, not a Content Management API client. The CDA does not give validation details, so this project doesn't work with it.

See [usage](https://github.com/intercom/contentful-typescript-codegen/tree/ce34c0b00ac05023314870fbacc8e7a1045eb346#usage). Please reopen if this doesn't fix the issue.
